### ISSUE TITLE
client Null pointer on rebalance

### ISSUE THREAD

**Issue by Arttii** [DataReply/kafka-connect-elastic-search-sink#3]
So if the Elastic Search client is not fully initialized and you push another config, which initiates a rebalanced the connect.stop() method kills the connector as the client is still NULL and we call client.close().

Should check if its already null and not do anything I think.

**Comment by spinatelli** [comment]
+1

**Comment by AlexPiermatteo** [comment]
+1

**Comment by patelliandrea** [comment]
go fuck yourself

**Comment by patelliandrea** [comment]
https://github.com/DataReply/kafka-connect-elastic-search-sink/commit/1b290ca2a5846a2e4ce0232dbb0463d07a8f8167
